/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-env.d.ts --env-interface CloudflareEnv --include-runtime false` (hash: f021c706d12cd880032f9de539f8bd19)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		BLOG_CACHE: KVNamespace;
		ASSETS: Fetcher;
		APP_ENV: "production";
		PUBLIC_SITE_URL: "https://sorcererxw.com";
		NOTION_BLOG_DATABASE_ID: "d6f20169e3b849059656e33a47e19003";
		NOTION_PROJECTS_DATABASE_ID: "63605072597640c4b666cd334b428aee";
		NOTION_INTRO_PAGE_ID: "ac63bdb57d224c41a951c0536396bdf4";
		NOTION_SECRET: string;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "PUBLIC_SITE_URL" | "NOTION_BLOG_DATABASE_ID" | "NOTION_PROJECTS_DATABASE_ID" | "NOTION_INTRO_PAGE_ID" | "NOTION_SECRET">> {}
}
